name: KenyaEMR CI

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Clean up previous build artifacts
        run: rm -rf openmrs-config-kenyaemr frontend

      - name: Install dependencies
        run: npm install

      - name: Build Kenya EMR 3.x assets
        run: npx --legacy-peer-deps openmrs@next build --build-config ./configuration/dev-build-config.json --target ./frontend --page-title "KenyaEMR" --support-offline false

      - name: Assemble assets
        run: npx --legacy-peer-deps openmrs@next assemble --manifest --mode config --config ./configuration/dev-build-config.json --target ./frontend

      - name: Copy and move required files
        run: |
          cp ./assets/kenyaemr-login-logo.png ./frontend
          cp ./assets/kenyaemr-primary-logo.png ./frontend
          cp ./assets/favicon.ico ./frontend
          cp ./configuration/dev-config.json ./frontend/config.json

      - name: Compress frontend folder
        run: tar -czvf frontend-${{ github.sha }}.tar.gz frontend/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-${{ github.sha }}.tar.gz
          path: frontend-${{ github.sha }}.tar.gz

      - name: Upload compressed frontend to server
        uses: appleboy/scp-action@v0.2
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.CICD_SECRET }}
          source: frontend-${{ github.sha }}.tar.gz
          target: /apps/githubworkflows/OpenMrs3.0_assets/

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.CICD_HOST }}
          username: ${{ secrets.CICD_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.CICD_SECRET }}
          script: |
            set -e
            cd /apps/githubworkflows/OpenMrs3.0_assets &&
            tar -xzf frontend-${{ github.sha }}.tar.gz &&
            sudo mv /var/lib/OpenMRS/frontend /var/lib/OpenMRS/frontend_old &&
            mv frontend /var/lib/OpenMRS/ &&
            sudo rm -rf /var/lib/OpenMRS/frontend_old

  release:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    if: github.event_name == 'release'
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Run production build script
        run: |
          chmod +x ./prod-build.sh
          ./prod-build.sh

      - name: Compress frontend folder for release
        run: tar -czvf frontend-release-${{ github.sha }}.tar.gz frontend/

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-release-${{ github.sha }}.tar.gz
          path: frontend-release-${{ github.sha }}.tar.gz
